{% set name = "pysqa" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysqa-{{ version }}.tar.gz
  sha256: f5503b500d6fc6397667fb1666e74c77efab789a2eddf1b2f8517223c69b85a8

build:
  entry_points:
    - pysqa=pysqa.cmd:command_line
    - pysqa-executor=pysqa.executor.backend:command_line
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jinja2 >=2.11.3,<=3.1.2
    - pandas >=1.5.3,<=2.1.3
    - pyyaml >=5.3.1,<=6.0.1

test:
  imports:
    - pysqa
  commands:
    - pip check
    - pysqa --help
  requires:
    - pip

about:
  home: https://github.com/pyiron/pysqa
  summary: pysqa - simple queue adapter
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
