{% set name = "pysqa" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0859ddcd761cff8ce5dff7e4dedf87064fa2464f297d691385e5aa6c7becfbe9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - defusedxml
    - pandas >=0.23
    - pyyaml
    - jinja2
    - paramiko
    - tqdm

test:
  imports:
    - pysqa

about:
  home: https://github.com/pyiron/pysqa
  license: BSD-3-Clause
  license_family: BSD
  license_file: 'LICENSE'
  summary: 'Simple queue adapter for Python'
  description: |
    The goal of pysqa is to make submitting to an HPC cluster as easy as starting another subprocess. 
    This is based on the assumption that even though modern queuing systems allow for an wide range of 
    different configuration, most users submit the majority of their jobs with very similar parameters. 
    Therefore pysqa allows the users to store their submission scripts as jinja2 templates for quick 
    access. After the submission pysqa allows the users to track the progress of their jobs, delete them 
    or enable reservations using the built-in functionality of the queuing system. The currently supported 
    queuing systems are: LFS, MOAB, SGE, SLURM, TORQUE.
  doc_url: https://github.com/pyiron/pysqa
  dev_url: https://github.com/pyiron/pysqa

extra:
  recipe-maintainers:
    - jan-janssen
    - pyiron-runner
