{% set name = "pysqa" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysqa-{{ version }}.tar.gz
  sha256: dd367773e313477b6b3bb1fcda40bf94b7e774dec20056035eeae4dd4e44cf28

build:
  entry_points:
    - pysqa=pysqa.base.cmd:command_line
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - jinja2
    - pandas
    - pyyaml
    - versioneer
    - toml
  run:
    - python >=3.7
    - jinja2 >=2.11.3,<=3.1.4
    - pandas >=1.5.3,<=2.2.3
    - pyyaml >=5.3.1,<=6.0.2

test:
  imports:
    - pysqa
  commands:
    - pip check
    - pysqa --help
  requires:
    - pip

about:
  home: https://github.com/pyiron/pysqa
  summary: pysqa - simple queue adapter
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
