{% set name = "pysqa" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysqa-{{ version }}.tar.gz
  sha256: daff734abe1b2eeabb6edfe972987f8bc0cf3ce3ccd2a62311a22d89d0ffa54b

build:
  entry_points:
    - pysqa=pysqa.base.cmd:command_line
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - jinja2
    - pandas
    - pyyaml
    - versioneer
    - toml
    - setuptools
  run:
    - python >={{ python_min }}
    - jinja2 >=2.11.3,<=3.1.6
    - pandas >=1.5.3,<=2.2.3
    - pyyaml >=5.3.1,<=6.0.2

test:
  imports:
    - pysqa
  commands:
    - pip check
    - pysqa --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pysqa
  summary: pysqa - simple queue adapter
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
