schema_version: 1

context:
  name: pysqa
  version: "0.3.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pysqa-${{ version }}.tar.gz
  sha256: 7ea1b42e457ef1a47367f68c3919e4ae904a01e6278157bdabe2e1527be612b6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pysqa=pysqa.base.cmd:command_line

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - jinja2
    - pandas
    - pyyaml
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - jinja2 >=2.11.3,<=3.1.6
    - pandas >=1.5.3,<=3.0.1
    - pyyaml >=5.3.1,<=6.0.3

tests:
  - python:
      imports:
        - pysqa
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - pysqa --help

about:
  summary: pysqa - simple queue adapter
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/pysqa

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
