schema_version: 1

context:
  name: pysqa
  version: "1.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pysqa-${{ version }}.tar.gz
  sha256: df06ebf225be73e3920d01e07a9bd763ad8acec1711e5700ca2cdfa62a8fa18c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pysqa=pysqa.base.cmd:command_line

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - jinja2
    - pandas
    - pyyaml
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - jinja2 >=2.11.3,<=3.1.6
    - pandas >=1.5.3,<=3.0.6
    - pyyaml >=5.3.1,<=6.0.3

tests:
  - python:
      imports:
        - pysqa
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - pysqa --help

about:
  summary: pysqa - simple queue adapter
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/pysqa

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
