travis:
  secure:
    BINSTAR_TOKEN: TBjc2IGHbJpJ8qTETknZsSSg6MEgdn/xdcyWGTRLrd39OBlXjSbt/1gBj8xfhpPdoef51bMJUm9QV1BOZsMMjWbIhRvG2J0dbsINJJ7RL96nYLYN4T+qYH7iUUWjlXF0Pm/hYV+8g+DIgzT+b5lq0IsUGFTgfuJR071YCjGKFGNL+JKlMLpltxonpsWQb9cJWgH6Z583vQkYVfZNWb61SKMBWy8wth+6jr7yuHYzEOOJBY+kf+W0UMxO8ZUfVmC4EysCF8pNwQy0VANqq1sEEFMXwlqVbeNUAlGM+pmvAZduac3wZZWqU5p1YC766FhwTSmsTgBEQAxeTbipsIvxWgwXQ2F89oyfYZlWYTU0OLALIvHz4aQMN0CIkuMIa7qEUpCs2GKxQ/XivnsCPcKoHafzMUeepyl7WeRuRZ1+oAEQdf8dEdDoBQSKqa8vejMoaNnN7/qo8rSO4STUMRSIJ41qLqVDuaSdBBhoD5gT2FZUA9tUGAVzOlA7+ji2swcFr15VrB8EQwV2UzEAIheASbwUKeJSqM2ld2VE9XU339E7jWJY0/IagNJrJzI1hPQBEdLoRrS4WurXL9vF5djfNcfoELHNP+XAOcbyXlTpssk57/zNWehTwgBWwOUr1c7qOlQXIIPYQyj0V2mh+FeZ++JFQWdcdFWoSFSHIwBS6n0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
